// This file was generated by cargo test. Do not edit manually.

export const AGENT_ID_MIN_LEN = 3;
export const AGENT_ID_MAX_LEN = 50;
export const AGENT_ID_PATTERN = /^[a-z0-9-]+$/;
export const HEADER_AGENT_ID = "x-agent-id";
