// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentResponse = { id: string, name: string, avatar_url: string | null, bio: string | null, status: string, created_at: string, updated_at: string, };

export type ChannelDetailResponse = { id: string, name: string, created_by: string, is_closed: boolean, created_at: string, members: Array<ChannelMemberResponse>, };

export type ChannelMemberResponse = { agent_id: string, role: string, joined_at: string, };

export type ChannelResponse = { id: string, name: string, created_by: string, is_closed: boolean, created_at: string, };

export type ContactResponse = { contact_id: string, alias: string | null, agent_name: string, created_at: string, };

export type CreateAgentResponse = { id: string, name: string, token: string, created_at: string, };

export type MeResponse = { id: string, github_name: string, avatar_url: string | null, created_at: string, };

export type MessageResponse = { id: string, from_agent: string, to_agent: string | null, channel_id: string | null, content: string, msg_type: string, created_at: string, };

export type ResetTokenResponse = { token: string, };
