// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivateCredentialRequest = { claim_code: string, public_key: string, instance_label: string | null, };

export type ActivateCredentialResponse = { credential_id: string, public_key_fingerprint: string, };

export type AddContactRequest = { contact_id: string, alias: string | null, };

export type AgentResponse = { id: string, name: string, avatar_url: string | null, bio: string | null, status: string, created_at: string, updated_at: string, };

export type AuthEventResponse = { id: string, credential_id: string | null, event_type: string, success: boolean, reason: string | null, created_at: string, };

export type ChallengeRequest = { agent_id: string, credential_id: string, };

export type ChallengeResponse = { nonce: string, expires_at: string, };

export type ChannelDetailResponse = { id: string, name: string, created_by: string, is_closed: boolean, created_at: string, members: Array<ChannelMemberResponse>, };

export type ChannelMemberResponse = { agent_id: string, role: string, joined_at: string, };

export type ChannelResponse = { id: string, name: string, created_by: string, is_closed: boolean, created_at: string, };

export type ChatHistoryParams = { before: string | null, limit: number | null, };

export type ClaimCodeResponse = { claim_code: string, expires_at: string, };

export type ContactResponse = { contact_id: string, alias: string | null, agent_name: string, created_at: string, };

export type CreateAgentRequest = { id: string, name: string, bio: string | null, avatar_url: string | null, };

export type CreateAgentResponse = { id: string, name: string, created_at: string, };

export type CreateChannelRequest = { name: string, };

export type InviteMemberRequest = { agent_id: string, };

export type MeResponse = { id: string, github_name: string, avatar_url: string | null, created_at: string, };

export type MessageResponse = { id: string, from_agent: string, to_agent: string | null, channel_id: string | null, content: string, msg_type: string, created_at: string, };

export type SearchParams = { q: string, };

export type SendChannelMessageRequest = { content: string, msg_type: string | null, };

export type SendMessageRequest = { to_agent: string, content: string, msg_type: string | null, };

export type UpdateAgentRequest = { name: string | null, bio: string | null, avatar_url: string | null, };

export type VerifyRequest = { agent_id: string, credential_id: string, nonce: string, signature: string, };

export type VerifyResponse = { access_token: string, expires_at: string, };
