#!/usr/bin/env bash
# ============================================================
# check-contracts.sh — 跨语言类型安全检测
#
# 检测 Rust ↔ TypeScript 实体契约违规：
#   1. 后端 #[ts(export)] 只能出现在 server/src/api/dto.rs
#   2. 前端不能重新定义 types.generated.ts 中已有的类型
#   3. 前端 src/api/ 使用后端类型必须从 types.generated.ts 导入
#   4. types.generated.ts 头部自动生成标记未被篡改
#
# 用法: bash scripts/check-contracts.sh
# ============================================================
set -euo pipefail

FAIL=0
WARN=0

SERVER_DIR="server"
FRONTEND_DIR="frontend"
DTO_FILE="$SERVER_DIR/src/api/dto.rs"
GENERATED_TS="$FRONTEND_DIR/src/api/types.generated.ts"
GENERATED_HEADER="// This file was generated by ts-rs"

red()    { printf "\033[31m%s\033[0m\n" "$1"; }
green()  { printf "\033[32m%s\033[0m\n" "$1"; }
yellow() { printf "\033[33m%s\033[0m\n" "$1"; }

echo "=== Cross-language contract check ==="
echo ""

# ============================================================
# 前置：目录存在性检查
# ============================================================
if [ ! -d "$SERVER_DIR/src" ]; then
    yellow "    SKIP: $SERVER_DIR/src not found (server not yet created)"
    echo ""
    echo "=== CONTRACT CHECK SKIPPED ==="
    exit 0
fi

# ============================================================
# Rule 1: #[ts(export)] 只能在 dto.rs 中
# ============================================================
echo "--- Rule 1: #[ts(export)] only in dto.rs ---"

# 搜索 server/src 下所有 .rs 文件中含 ts(export 的行，排除 dto.rs
VIOLATIONS=$(find "$SERVER_DIR/src" -name '*.rs' \
    ! -path "$DTO_FILE" \
    -exec grep -Hn '#\[ts(export' {} \; 2>/dev/null || true)

if [ -n "$VIOLATIONS" ]; then
    red "    FAIL: #[ts(export)] found outside dto.rs:"
    echo "$VIOLATIONS" | sed 's/^/    /'
    FAIL=1
else
    green "    PASS"
fi
echo ""

# ============================================================
# Rule 2: dto.rs 必须存在（如果有任何 ts(export 使用）
# ============================================================
echo "--- Rule 2: dto.rs exists if ts(export) is used ---"

HAS_TS_EXPORT=$(find "$SERVER_DIR/src" -name '*.rs' \
    -exec grep -l '#\[ts(export' {} \; 2>/dev/null || true)

if [ -n "$HAS_TS_EXPORT" ] && [ ! -f "$DTO_FILE" ]; then
    red "    FAIL: ts(export) used but $DTO_FILE does not exist"
    FAIL=1
elif [ -z "$HAS_TS_EXPORT" ]; then
    yellow "    SKIP: no ts(export) usage yet"
else
    green "    PASS"
fi
echo ""

# ============================================================
# 前端检测（仅在 frontend 目录存在时）
# ============================================================
if [ ! -d "$FRONTEND_DIR/src" ]; then
    yellow "    SKIP: $FRONTEND_DIR/src not found (frontend not yet created)"
    echo ""
    echo "=== CONTRACT CHECK DONE (partial — frontend missing) ==="
    [ "$FAIL" -eq 0 ] && exit 0 || exit 1
fi

# ============================================================
# Rule 3: types.generated.ts 头部标记完整
# ============================================================
echo "--- Rule 3: generated file header intact ---"

if [ -f "$GENERATED_TS" ]; then
    FIRST_LINE=$(head -1 "$GENERATED_TS")
    if [[ "$FIRST_LINE" != "$GENERATED_HEADER"* ]]; then
        red "    FAIL: $GENERATED_TS header tampered (expected: $GENERATED_HEADER)"
        FAIL=1
    else
        green "    PASS"
    fi
else
    yellow "    SKIP: $GENERATED_TS not yet generated"
fi
echo ""

# ============================================================
# Rule 4: 前端 src/api/ 中的后端类型只能从 types.generated.ts 导入
# ============================================================
echo "--- Rule 4: frontend api/ imports only from types.generated ---"

if [ -f "$GENERATED_TS" ]; then
    # 提取 generated 中导出的类型名
    GENERATED_TYPES=$(grep -oE 'export (interface|type|enum) (\w+)' "$GENERATED_TS" \
        | awk '{print $3}' | sort -u)

    if [ -n "$GENERATED_TYPES" ]; then
        # 在 src/api/ 的非 generated 文件中，查找从其他地方 import 这些类型的情况
        API_FILES=$(find "$FRONTEND_DIR/src/api" -name '*.ts' -o -name '*.tsx' \
            | grep -v 'types.generated.ts' 2>/dev/null || true)

        IMPORT_VIOLATIONS=""
        for f in $API_FILES; do
            [ -z "$f" ] && continue
            for t in $GENERATED_TYPES; do
                # 查找 import { ... Type ... } from 不是 types.generated 的来源
                BAD=$(grep -n "import.*\b${t}\b" "$f" \
                    | grep -v 'types.generated' \
                    | grep -v '^\s*//' 2>/dev/null || true)
                if [ -n "$BAD" ]; then
                    IMPORT_VIOLATIONS="${IMPORT_VIOLATIONS}${f}: ${BAD}\n"
                fi
            done
        done

        if [ -n "$IMPORT_VIOLATIONS" ]; then
            red "    FAIL: backend types imported from non-generated source:"
            echo -e "$IMPORT_VIOLATIONS" | sed 's/^/    /'
            FAIL=1
        else
            green "    PASS"
        fi
    else
        yellow "    SKIP: no exported types in generated file"
    fi
else
    yellow "    SKIP: $GENERATED_TS not yet generated"
fi
echo ""

# ============================================================
# Rule 5: 前端不能重新定义 generated 中的类型
# ============================================================
echo "--- Rule 5: no re-definition of generated types ---"

if [ -f "$GENERATED_TS" ] && [ -n "${GENERATED_TYPES:-}" ]; then
    REDEF_VIOLATIONS=""
    # 搜索 frontend/src 下除 generated 之外的文件
    FRONTEND_FILES=$(find "$FRONTEND_DIR/src" \( -name '*.ts' -o -name '*.tsx' \) \
        ! -name 'types.generated.ts' 2>/dev/null || true)

    for f in $FRONTEND_FILES; do
        [ -z "$f" ] && continue
        for t in $GENERATED_TYPES; do
            # 查找 interface X { 或 type X = 的重新定义
            BAD=$(grep -nE "^export (interface|type) ${t}\b" "$f" 2>/dev/null || true)
            if [ -n "$BAD" ]; then
                REDEF_VIOLATIONS="${REDEF_VIOLATIONS}${f}: ${BAD}\n"
            fi
        done
    done

    if [ -n "$REDEF_VIOLATIONS" ]; then
        red "    FAIL: re-definition of generated types:"
        echo -e "$REDEF_VIOLATIONS" | sed 's/^/    /'
        FAIL=1
    else
        green "    PASS"
    fi
else
    yellow "    SKIP: no generated types to check"
fi
echo ""

# ============================================================
# 结果
# ============================================================
if [ "$FAIL" -ne 0 ]; then
    red "=== CONTRACT CHECK FAILED ==="
    exit 1
fi

green "=== CONTRACT CHECK PASSED ==="
